export const GET_HOTEL_REQUEST = 'GET_HOTEL_REQUEST';
export const GET_HOTEL_SUCCESS = 'GET_HOTEL_SUCCESS';
export const GET_HOTEL_FAILED = 'GET_HOTEL_FAILED';
export const ADD_FAVORITES_HOTEL = 'ADD_FAVORITES_HOTEL';
export const DELETE_FAVORITES_HOTEL = 'DELETE_FAVORITES_HOTEL';
